name: Release sync

on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    name: Cherry pick into release branch
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Obtain release
        run: |
          labels='${{ toJSON(github.event.pull_request.labels.*.name) }}'
          release_label=$(jq '.[] | select(contains("release:"))' <<< $labels)
          version=$(sed "s/release://g" <<< $release_label)
          echo "TARGET_VERSION=$version" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into ${{ env.TARGET_VERSION }}
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: ${{ env.TARGET_VERSION }}
          labels: cherry-pick
          # reviewers: aReviewerUser