name: Changesets status

on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - id: files
        name: Get changed files
        uses: jitterbit/get-changed-files@v1
        with:
          format: csv
      - name: Changeset file lookup  
        run: |
          echo "${{ steps.files.outputs.added_modified }}"
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo "Do something with this ${changed_file}."
          done