name: Changesets status

on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for added_file in ${{ steps.files.outputs.added_modified }}; do
            echo "${added_file} | grep "\.changeset\/.*\.md"
          done