name: Changesets status

on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      # - name: Checkout Repo
      #   uses: actions/checkout@v3

      - name: Changeset file lookup       
        run: |
          pr_branch="${{ github.ref }}"
          echo "branch: $pr_branch"
          names=$(gh pr diff $pr_branch --name-only)
          echo "files: $names"
          # if [[ "${{ steps.files.outputs.added_modified }}" =~ \.changeset\/.*.md ]]; then
          #   echo "Changesets found!"
          # else
          #   echo "There is no changeset file in your pull request."
          #   exit 1
          # fi
          