name: Changesets status

on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          has_file=false
          for added_file in ${{ steps.files.outputs.added_modified }}; do
            has_file=$(echo "${added_file}" | grep "\.changeset\/.*\.md")
          done

          echo "has file: $has_file"