name: Release event etst

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      # Tags stable versions as :latest
      # Pre-releases, alphas, etc. as :snapshot
      - name: Output image tags from git tag events
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          CURRENT_VERSION=$(gh api repos/andrzejewsky/changesets-playground/releases/latest | jq .tag_name | xargs)
          TAG_VERSION=${GITHUB_REF#refs/tags/}

          echo "Current: $CURRENT_VERSION"
          echo "Tag: $TAG_VERSION"

          if [ "$CURRENT_VERSION" = "$TAG_VERSION" ]; then
            DASHBOARD_VERSION=latest
          else
            DASHBOARD_VERSION=$TAG_VERSION
          fi

          echo "
          DASHBOARD_VERSION=${DASHBOARD_VERSION}
          CONTAINER_TAGS=${{ steps.image.outputs.image_name }}:${DASHBOARD_VERSION}
          " >> "${GITHUB_ENV}"

      - name: Output test
        run: |
          echo "event: ${{ toJson(github.event) }}"
          echo "Tags: ${{ env.CONTAINER_TAGS }}"