name: Release event etst

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      # Tags stable versions as :latest
      # Pre-releases, alphas, etc. as :snapshot
      - name: Output image tags from git tag events
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LATEST_VERSION=$(gh api repos/andrzejewsky/changesets-playground/releases/latest | jq -r .tag_name)
          CURRENT_TAG=${GITHUB_REF#refs/tags/}

          if [ "$LATEST_VERSION" = "$CURRENT_TAG" ]; then
            TAGS=repo:${CURRENT_TAG},repo:latest
          else
            TAGS=repo:${CURRENT_TAG}
          fi

          echo "
          DASHBOARD_VERSION=${CURRENT_TAG}
          CONTAINER_TAGS=${TAGS}
          " >> "${GITHUB_ENV}"

      - name: Output test
        run: |
          echo "Tags: ${{ env.CONTAINER_TAGS }}"